server:
  port: 8080
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.eatery.cd.pojo

